from typing import TypedDict, Annotated, Sequence, Optional
from langchain_core.messages import BaseMessage
import operator

class SDKJobState(TypedDict):
    # ── Core conversation ─────────────────────────────────────────────────
    # Every agent appends messages here. Supervisor reads all of them.
    messages: Annotated[Sequence[BaseMessage], operator.add]

    # ── Job metadata ──────────────────────────────────────────────────────
    job_id: str
    target_url: str
    language: str        # "python" | "typescript"
    page_content: str    # landing page text — injected by Chrome extension
    page_links: list[dict] # [{"text": "Auth", "href": "/docs/auth", "inNav": True}, ...]

    # ── Researcher outputs ────────────────────────────────────────────────
    crawl_plan: Optional[list[dict]]    # LLM-selected pages to crawl
    crawled_pages: Optional[list[dict]] # pages actually scraped
    knowledge_base: Optional[dict]      # structured research output

    # ── Architect outputs ─────────────────────────────────────────────────
    api_schema: Optional[dict]          # validated, structured endpoint schema
    schema_fixes: list[str]             # list of auto-fixes applied by Architect

    # ── Engineer outputs ──────────────────────────────────────────────────
    sdk_files: Optional[dict]           # {"client.py": "...", "models.py": "...", ...}
    syntax_errors: list[str]            # syntax issues found and fixed internally

    # ── QA Tester outputs ─────────────────────────────────────────────────
    test_results: Optional[list[dict]]  # test case results
    qa_iteration: int                   # how many QA rounds have run

    # ── Packager outputs ──────────────────────────────────────────────────
    final_files: Optional[dict]         # linted, final files sent to VS Code
    narration_text: Optional[str]       # spoken summary generated by LLM

    # ── Routing & control ─────────────────────────────────────────────────
    next_agent: str
    iteration_count: int      # total graph iterations — safety ceiling: 15
    status: str               # "running" | "success" | "failed"
    failure_reason: Optional[str]

    # ── SSE event queue (append-only, consumed by FastAPI stream endpoint) ─
    sse_events: Annotated[list[dict], operator.add]

def build_state_summary(state: SDKJobState) -> str:
    """Helper to summarize state for the Supervisor LLM."""
    import json
    summary = {
        "job_id": state["job_id"],
        "target_url": state["target_url"],
        "language": state["language"],
        "status": state["status"],
        "iteration_count": state["iteration_count"],
        "has_knowledge_base": state["knowledge_base"] is not None,
        "has_api_schema": state["api_schema"] is not None,
        "has_sdk_files": state["sdk_files"] is not None,
        "qa_iteration": state["qa_iteration"]
    }
    return json.dumps(summary, indent=2)

def emit_sse(state: SDKJobState, event_type: str, **kwargs) -> SDKJobState:
    """Helper to append an SSE event to the queue."""
    # In LangGraph, to update a state field that uses operator.add,
    # you return a dict with the field and the item(s) to add.
    event = {"type": event_type, **kwargs}
    return {"sse_events": [event]}
